// ============================================================
// utilities.types.ts - Export all types from the utilities slice
// ============================================================


export type {
  UtilityType,
  UtilityStatus,
  UtilityApprovalStatus,
  MemoStatus,
  ConsolidatedMemoType,
  UtilityItem,
  JudgeUtility,
  ConsolidatedMemo,
  UtilityItemInput,
  CreateUtilityInput,
  AddUtilityItemInput,
  UpdateUtilityItemInput,
  UpdateUtilityInput,
  UtilityFilters,
  GenerateMemoInput,
  MemoFilters,
  BulkUpdateUtilityItemsInput,
  UtilityStats,
  MemoSummary,
} from "../store/slices/utilitiesSlice";

export {
  // Default export is the reducer
  default as utilitiesReducer,
  // Named exports for thunks
  fetchUtilities,
  fetchUtilityById,
  fetchUtilityByPjNumber,
  createUtility,
  addUtilityItem,
  updateUtilityItem,
  updateUtility,
  deleteUtilityItem,
  deleteUtility,
  fetchMemos,
  fetchMemoById,
  fetchMemoByEntityId,
  generateMemo,
  sendMemoForApproval,
  approveMemo,
  rejectMemo,
  cancelMemo,
  fetchPendingUtilities,
  fetchUtilitiesByApprovalStatus,
  fetchAvailablePeriods,
  fetchUtilitySummary,
  fetchUtilityStats,
  fetchUtilityEnums,
  bulkUpdateUtilityItems,
  // Actions
  setUtilityFilters,
  setMemoFilters,
  clearUtilityFilters,
  setUtilityPagination,
  setMemoPagination,
  setSelectedUtility,
  setSelectedMemo,
  updateUtilityItemOptimistically,
  updateMemoOptimistically,
  clearUtilityError,
  clearUtilitySuccess,
  resetUtilitiesState,
  // Selectors
  selectAllUtilities,
  selectAllMemos,
  selectAllUtilityItems,
  selectSelectedUtility,
  selectSelectedMemo,
  selectUtilityFilters,
  selectMemoFilters,
  selectUtilitiesLoading,
  selectMemosLoading,
  selectUtilitiesMutating,
  selectUtilitiesGenerating,
  selectUtilitiesStatsLoading,
  selectUtilityStats,
  selectMemoSummary,
  selectAvailablePeriods,
  selectUtilitiesByStatus,
  selectMemosByStatus,
  selectMemosByType,
  selectMemosByPeriod,
  selectPendingItemsCount,
  selectSentItemsCount,
  selectApprovedItemsCount,
  selectRejectedItemsCount,
  selectTotalUtilityAmount,
  selectUtilityItemsByPeriod,
  selectPendingUtilityItemsByPeriod,
  selectItemsByApprovalStatus,
  selectUtilitiesPagination,
  selectMemosPagination,
  selectUtilitiesError,
  selectUtilitiesSuccess,
} from "../store/slices/utilitiesSlice";